### PR TITLE
Created a new branch and managed to recover files from old commit on …

### PR DESCRIPTION
**Pull request by GODOmegaPi**
…88 branch

### CODE REVIEW

**Comment by GODOmegaPi** [comment]
I've done the required modifications. It should be good to merge

**Comment by wasadigi** [comment]
Ok, I still see 3 beers in the PR (in "Files changed"). Do you know how to split it? If you want, we can look at it together (or if you have the lab today, you can talk with Guillaume). Otherwise, let me know and I will merge it like that.

**Comment by GODOmegaPi** [comment]
For my two oppenned PR, I have no idea on how to fix this. Last time I've checed this with you and I was supposing that this was good. If you can merge my two oppenned PR I would appreciate it and I'd like you to explain me how to fix this next time if you have some time please.

**Comment by wasadigi** [comment]
Here is the general idea, but it might be better if we take some time to work together on the machine:

1. I am on master, I do a "checkout -b feature-1", implement the feature 1, push my commit and open a PR
2. This one is clean
3. I FORGET to "checkout master" and do "checkout -b feature-2" immediately
4. I implement feature 2, push my commit and open a 2nd PR
5. wasadigi complains, because on the PR, he sees commits of feature 1 and of feature 2

One way to fix this would be to use the rebase command and to force push the branch... but force push can be dangerous, so let's forget about that for now.

Another way to do this is to create a new branch and to open a new PR (and then to close the "broken" one):

1. git checkout master: Go back to master, what should have been done in the first place
2. git checkout -b feature-2-clean: create a new branch
3. now is the interesting part: how do we retrieve the PR2 files that we already wrote before?
4. git checkout feature-2 -- src/main/.../Toto.java (take Toto.java from previous branch)
5. git checkout feature-2 -- src/test/.../TotoTest.java (same thing, path to the test file)
6. git add .
7. git commit -m "Add Toto feature with test"
8. git push origin feature-2-clean
9. go to GitHub, open the new PR
10. close the broken one

That is a safe way to do it (please test the commands, I wrote them on the stop and did not retest them, so it's possible I missed something). Using rebase would allow us to stay on the same PR, but I would to have a bit more practice with git to use that.

**Pull request closed without merging**
