### PR TITLE
Add LaPecheresse to the bar

### LINKED ISSUE #479: Add La Pecheresse
Adding La Pecheresse to the bar

### PR DESCRIPTION
**Pull request by Cell00phane**
Closes #479

### CODE REVIEW

**Comment by Cell00phane** [comment]
Closes #482

**Comment by wasadigi** [comment]
Did you see that you have 2 beers on this PR? Can you please try to split it in two? Thanks!

**Comment by Cell00phane** [comment]
Yes. They are two different commits but apparently Git added the second commit automatically to the same pull request I opened with the first one since they're both linked to my repo. I'll try and split them.

**Comment by wasadigi** [comment]
Ok, cool. Let us know if you have problems.

**Comment by Cell00phane** [comment]
As to the problem with the test package renaming to Test, I think this originated in my IDE. I'm not sure how but the test package default name in my IDE starts with a capital 'T' and I didn't notice it since it was still showing as one test package containing all the tests (except its name was Test instead of test). And after I made my first commit with Duff, git recognized it as two separate test packages and pushed it as such. So now on the remote there was two test packages while on my IDE and maybe others, it was still one test package. 

I first noticed it when someone did a commit involving moving my files from 'Test' to 'test'. So on my next commits I renamed my test package on IntelliJ to 'test' and moved everything to its right place. These commits are the ones pending on this current pull request.

Sorry for the confusion xx

**Comment by wasadigi** [comment]
No problem at all, and thank you very much for the feedback. It's funny because looking at the git history, I though Didier introduced the change. I'll got back to the history :-).

**Comment by Cell00phane** [comment]
I may also be wrong. Maybe someone else introduced the error and I fixed it. As I said this was noticed pretty late by me.

**Pull request merged**
