### PR TITLE
Fb jus de chaussette

### LINKED ISSUE #543: Ajoute de jus de chaussette
Il en faut pour tous les goûts. La première brassée est en route.

### PR DESCRIPTION
**Pull request by Dherleth**
Closes #543

### CODE REVIEW

**Comment by wasadigi** [comment]
Thanks for the PR, but you have too many files in there. Can you please remove the eclipse files and push a commit to the branch?

**Comment by Dherleth** [comment]
What do you mean by eclipse files ? If you meant the IDE, I don't use it. My git status only told me about my two java files before I added src. I checked my local repo, I don't see anything wrong.

**Comment by Dherleth** [comment]
Oh, I see a .settings from a commit four days ago. Didn't know where they came from. I'll remove the directory

**Comment by wasadigi** [comment]
Thanks! But you still have a couple of files in the PR. Can you please remove them?

**Pull request merged**
