### PR TITLE
SuperBock,Cardinal and CocaCola added

### PR DESCRIPTION
**Pull request by joshuaGomesDaCosta**
I added the class SuperBock, Cardinal and CocaCola in the domain joshuaGomesDaCosta.

### CODE REVIEW

**Comment by joshuaGomesDaCosta** [comment]
@ #293

**Comment by joshuaGomesDaCosta** [comment]
#295

**Comment by wasadigi** [comment]
Thanks for the PR. I could merge like that, but you have 2 "features" in the same PR. I prefer to have one PR per feature. Could you please try to break this one in two (the goal is for you to try a couple of git commands).

https://gist.github.com/Loilo/930f141d9acf89e9e734ffa042acd750

Have a look at this description. If you don't understand what's going on, let's look at it together next week.

**Comment by joshuaGomesDaCosta** [comment]
You can close this PR. I couldn't split the feature because I commit the 3 class in the same commit.

**Comment by joshuaGomesDaCosta** [comment]
I forget to precise without merging because I already PR separately the 3 class

**Comment by wasadigi** [comment]
Thanks for the update (next time, you can also directly close the PR yourself). Thanks also for the 3 other PRs!

**Pull request closed without merging**
