### PR TITLE
Add Friswein

### PR DESCRIPTION
**Pull request by Crulllo**
I've created and tested a new beer called Friswein.

### CODE REVIEW

**Comment by wasadigi** [comment]
Who authorized you to change the specs ;-) ? Please do not change the Bartender.java class (nor the test that we have provided). Please restore the initial state and push a new commit on this PR. Thanks!

**Comment by Crulllo** [comment]
I'm really sorry for that. Is everything okay now ?

**Comment by Crulllo** [comment]
I'm really sorry for that. Is everything okay now ?

**Comment by wasadigi** [comment]
Perfect, thanks!

**Pull request merged**
