### PR TITLE
Fb add omuraisu

### PR DESCRIPTION
**Pull request by RengokuryuuHonokaCrimsonFlame**
I've implemented Omuraisu to menu. You can close this issue, #566.

### CODE REVIEW

**Comment by wasadigi** [comment]
Hi there. Two small problems here:

- you have two beverages in the same PR, it would be better to split them
- you are DELETING pagedidier's file. Can you please try to restore the file that is currently on upstream/master?

**Comment by RengokuryuuHonokaCrimsonFlame** [comment]
I tried to reimport the upstream master on my computer, but it doesn't seem to be working…
(git fetch upstream + git rebase upstream/master)
Which git command must I use in this case ?

**Comment by RengokuryuuHonokaCrimsonFlame** [comment]
I tried to reimport the upstream master on my computer (git fetch upstream + git rebase upstream/master), but it doesn't seem to be working…

Which git command must I use in this case ?

**Comment by wasadigi** [comment]
In principle:

- git checkout master
- git pull upstream master
- git checkout fb-add-omuraisu
- git checkout master -- path/to/the/file/to/restore

**Comment by RengokuryuuHonokaCrimsonFlame** [comment]
When I try this, I've got the Following error : 
capture

**Comment by RengokuryuuHonokaCrimsonFlame** [comment]
Ok, it seems to work with '/' but not with '\'... I push the fixing problem with push -f to avoid the rejection.

**Comment by wasadigi** [comment]
Ok, well done on the test file. Now... you have 2 products on this PR. Can you try to only keep the Omuraisu?

**Comment by RengokuryuuHonokaCrimsonFlame** [comment]
I make the modification as requested.

**Comment by wasadigi** [comment]
That's not what you are trying to do. If you do a git rm, it will remove the file from the repo. If I merge this, ChiffonCake will be gone from the codebase. Easiest fix is to create a new branch and a new pull request. See #448 (my comment in this PR)

**Comment by RengokuryuuHonokaCrimsonFlame** [comment]
Ok, I created a new branch.
https://github.com/SoftEng-HEIGVD/Teaching-HEIGVD-RES-2019-Chill/pull/755

**Comment by wasadigi** [comment]
So I guess you can close this PR, right?

**Comment by RengokuryuuHonokaCrimsonFlame** [comment]
Ok.

**Pull request closed without merging**
