### PR TITLE
Fb delafonataine

### LINKED ISSUE #374: Add De La Fontaine
I would like the worst beer please

### PR DESCRIPTION
**Pull request by samirkovitch**
Do not accepte this beer please. It should close #374

### CODE REVIEW

**Comment by wasadigi** [comment]
Too many files in this PR: I see both Santamaria and Delafontaine. The reason is most likely that you created the 2nd feature branch when you were still on the 1st feature branch (instead of going back to master).

**Comment by samirkovitch** [comment]
I have a problem to fix this commit: i don't have the files DeLaFontaine.java and SantaMaria.java on my computer. I think they were deleted when i tried to git pull upstream master the first time.

**Comment by wasadigi** [comment]
On which branch are you? If you "checkout fb-delafontaine", you should see them (unless maybe you merged upstream onto this branch?)

**Comment by samirkovitch** [comment]
I was on master. I understood how it works yesterday evening.

**Comment by wasadigi** [comment]
But I still see 4 modified files. Do you have problems removing it?

**Comment by samirkovitch** [comment]
I had some problems to remove it. I asked to Guillaume help. We tried to merge fb-delafonataine with my master but it failed. So we tried to force merge. It worked but one Santamaria file stayed and a DelaFontaine file was assemblied with a anther.
Guillaume said it will be easier to start a new correct branch.

**Pull request closed without merging**
