### PR TITLE
new beer garlic beer

### PR DESCRIPTION
**Pull request by tranqui793**
what about Garlic Beer ?

### CODE REVIEW

**Comment by wasadigi** [comment]
Please remove pom.xml from the PR. I see that you had a problem, but what exactly? It should work, so we need to look at your system to see if you have something particular.

**Comment by tranqui793** [comment]
yes i have something in particular i had a problem with maven and i looked with miguel and the solution was to a configuration

**Comment by wasadigi** [comment]
@edri lied ;-). I don't want to change pom.xml, it should work. However, one student added by mistake an import (and depending on the JDK, I think that this created the issue). Can you please restore pom.xml, pull everything from upstream and let us know if you still have issues?

**Comment by tranqui793** [comment]
ok so i need to do other pull request without pushing pom.xml ?

**Comment by tranqui793** [comment]
because when i pulled everything for the upstream my local pom.xml dosen't change

**Comment by wasadigi** [comment]
I take this back, now I understand why @edri proposed this fix. There was another problem, with another student, and I thought the 2 were related.

For reference: https://stackoverflow.com/questions/53010200/maven-surefire-could-not-find-forkedbooter-class

**Comment by wasadigi** [comment]
Upgrading surefire to 3.0.0-M3 also fixed the problem.

**Comment by edri** [comment]
Hi there! I indeed found the pom.xml solution to this openjdk issue in the stackoverflow thread you just mentionned above, and gave it to @tranqui793. Glad to know that the upgrade of the plugin fixed it!

**Pull request merged**
