### PR TITLE
first version of Club-Mate

### PR DESCRIPTION
**Pull request by ncdm-stldr**
I added a ClubMate class as well as an associated unit test. It implements  IProduct, and is aimed to represent a beverage.

### CODE REVIEW

**Comment by wasadigi** [comment]
Ok, we have a small problem with this PR and I cannot merge it like that (there is a conflict). Here is what happened:

- yesterday, I changed the .gitignore file to remove chill.iml and the .idea folder
- you did not do a "pull upstream master" before opening your PR, which means that you still have the old .gitignore
- for this reason, you have a chill.iml file in your commit (and this causes a conflict: you modify a file that does not exist anymore)

You need to remove chill.iml from this branch (with a new commit). I can then merge. Also, pull changes from upstream, so that you have the new code in your clone (the contributions from other students).

**Comment by ncdm-stldr** [comment]
ok. I wondered why there was this conflict. It makes sense.
I updated my repository. It should now contain the new version on chill.iml (as well as some contributions of other student pulled from this repo).
I am unsure about what I should do know. Simply notify you with this message and you'll see if you can merge?

**Comment by wasadigi** [comment]
Given the number of PR, it's a bit tricky for me to keep up with modifications (which is why I only come back to you know). You can add a @wasadigi in the message.

**Comment by ncdm-stldr** [comment]
#304

**Pull request merged**
