### PR TITLE
Fb cuvee

### LINKED ISSUE #417: Add Cuvée des Trolls
Let me add a new beer.

### PR DESCRIPTION
**Pull request by linois**
Closes #417

### CODE REVIEW

**Comment by wasadigi** [comment]
Did you see that you have 2 beers on this PR? Can you please try to split it in two? Thanks!

**Comment by linois** [comment]
Sorry, I didn't see it... I'm trying to correct it.

Le mer. 27 févr. 2019 à 15:21, Olivier Liechti <notifications@github.com> a
écrit :

**Comment by linois** [comment]
I just corrected the files and sent them through the push, however I can't Comapre an pull request. Did it pass ?

**Comment by wasadigi** [comment]
So, the corrections in the file (name change) worked fine. But you still have the problem that there are 2 beers (4 files). To fix, see my comment in https://github.com/SoftEng-HEIGVD/Teaching-HEIGVD-RES-2019-Chill/pull/448.

**Pull request closed without merging**
