### PR TITLE
Fb adding matcha tea

### PR DESCRIPTION
**Pull request by ncdm-stldr**
Hi,
I added the class MatchaTea. This is a new  IProduct

### CODE REVIEW

**Comment by wasadigi** [comment]
Can you please update the branch, so that there are only the 2 files required for matcha? Now, I also have  club (probably because you created the 2nd feature branch when you were still on the first feature branch (instead of going back to master).

Also, we have a problem with the Test package (with a capital T). I am currently investigating to understand where this comes from. It's a little bit tricky to fix (depending on the OS). You should be able to do that:

- git mv Test test2
- git commit -m "fix uppercase Test package, step 1"
- git mv test2 test
- git commit -m "fix uppercase Test package, step 2"

(assuming that you are on a terminal, in the folder containing the test package). Please let us know if that works or if you have problems.

**Comment by ncdm-stldr** [comment]
@wasadigi It seems to work. I updated the branch.

**Comment by wasadigi** [comment]
Nice! The "T"est is fixed. I still see 2 beverages. If you want, you can try to split the PR in 2. If you don't want to do it, let me know and I will merge the PR like that.

**Comment by ncdm-stldr** [comment]
@wasadigi  I see know that I forget to do the final push. Now I did it and I should have only 2 new files in the branch (MatchaTea.java and MatchaTeaTest.java)

**Comment by wasadigi** [comment]
Looks good to me!

**Pull request merged**
