### PR TITLE
Add Truan

### LINKED ISSUE #498: Add Truan
Forgot to add first the issue. I would like to add the beer Truan

### PR DESCRIPTION
**Pull request by samirkovitch**
Add the beer Truan. Closes #498

### CODE REVIEW

**Comment by wasadigi** [comment]
63 files... from the other repo...? Writing beer classes is not drinking them.

**Comment by samirkovitch** [comment]
I am not sur about what i did

**Comment by wasadigi** [comment]
Probably typed git remote add upstream with url of the main course repo when you were in the clone of the chill repo. Check with git remote -v

**Comment by wasadigi** [comment]
You still have CONTRIB.md in the PR

**Comment by samirkovitch** [comment]
okay nerver clone 2 repo in the same folder
Normally i remove every files that should not be modified

**Pull request merged**
