### PR TITLE
new attempt to add IProduct JaggerMeister

### PR DESCRIPTION
**Pull request by ncdm-stldr**
This is a new pull request to add JaggerMeister. It was simpler for me to create a new pull request. My old pull request is also closed.
I removed my old branch fb-adding-jagger_meister from my repo and created it again with the same name, because I wasn't able to do what I wanted: I had previously deleted my git folder on my computer, then cloned my master branch again from my repo (I restarted from sratch), then created the branch fb-adding-jagger_meister also from scratch on my computer.

### CODE REVIEW

**Comment by ncdm-stldr** [comment]
I have the same problem as before. I don't understand why.
It say there are 4 files changed:
-MatchaTea.java and MatchaTeaTest.java are missing (which is normal since I don't mind these files here, but only JaggerMeister.java and JaggerMeisterTest.java)
-ClubMate.java was replaced by JaggerMeister.java and same for their test conterparts. I don't see why it thinks like JaggerMeister replaced ClubMate. I did some "git rm" to remove ClubMate.java, and later added JaggerMeister.java

**Comment by wasadigi** [comment]
Ok, I need to take a look.

**Comment by wasadigi** [comment]
The problem is that if you do a "git rm", then it really means "remove this file from the REPO" (not from the PR. So, we would lose the feature.

It was a good idea to create a new branch. Where you back on master when you did that?

When you are on a new branch and you want to retrieve a file that is available on another branch, do you know how to use the command "git checkout branch_name -- file/path"?

**Comment by ncdm-stldr** [comment]
> The problem is that if you do a "git rm", then it really means "remove this file from the REPO" (not from the PR. So, we would lose the feature.
I am not sure to understand what this means.

> It was a good idea to create a new branch. Where you back on master when you did that?
Yes, I created the branch from my master branch. I then added the new features and removed (git rm ...) the features I added in other PR (because my current master branch contains the contributions of my 2 other PR)

> When you are on a new branch and you want to retrieve a file that is available on another branch, do you know how to use the command "git checkout branch_name -- file/path"?
I once saw that this command but then I forget about it. thanks for reminding me about it, it is quite useful.

**Comment by ncdm-stldr** [comment]
@wasadigi In my last commit I still have the contributions from my other feature branches. I saw you sent a link on telegram that explains how to avoid this (I am talking about https://github.com/SoftEng-HEIGVD/Teaching-HEIGVD-RES-2019-Chill/pull/448). I will read it and try to fix the problem.

**Comment by ncdm-stldr** [comment]
I read the explanation. The thing is, my master branch contains my contributions from past pr, because I pulled from upstream. So creating a new fb from master will still contains the files from other PRs I made.
So I suppose, when I create a new feature branch, I should do it from an old version of my master branch?

**Comment by ncdm-stldr** [comment]
@wasadigi  So I'll do as you explained on telegram. I created fb-adding-JaggerMeister-clean. I'll create a new pull request. I should close this one I guess.

**Pull request closed without merging**
