### PR TITLE
Adding tea to the card

### PR DESCRIPTION
**Pull request by nfluckiger**

### CODE REVIEW

**Comment by wasadigi** [comment]
These files don't contain any code, are you sure you wanted to open the PR at this stage?

**Comment by wasadigi** [comment]
Just to make clear: this is NOT a valid PR.

**Comment by nfluckiger** [comment]
> Just to make clear: this is NOT a valid PR.

I know, I will make it valid befor sunday 23h

**Comment by wasadigi** [comment]
Ok, good.

**Comment by wasadigi** [comment]
Please fix method names in Test class (boxer vs tea)

**Pull request merged**
