### PR TITLE
Add Jelen with tests

### LINKED ISSUE #128: Adding "Jeleno Pivo" beer
I will add "Jeleno Pivo" beer now.

### PR DESCRIPTION
**Pull request by panticne**
Close #128

### CODE REVIEW

**Comment by panticne** [comment]
Est-ce que ce PR est bon?

**Comment by wasadigi** [comment]
Almost: the name of your test method is wrong (still uses Brooklyn). But that's easy to fix with a commit.

**Comment by panticne** [comment]
Normalement c'est bon

**Comment by wasadigi** [comment]
Nope: the name of the test METHODS are still wrong.

**Comment by wasadigi** [comment]
That one is good.

**Pull request merged**
